name: e_commerce
description: "Practical Task"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.2
  connectivity_plus: ^4.0.2
  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  url_launcher: ^6.3.0
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  objectbox: ^4.0.2
  objectbox_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  objectbox_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/flags/
    - assets/fonts/
    - assets/fonts/plus_jakarta/
    - assets/fonts/grandis_extended/
    - assets/icons/
    - assets/images/
    - assets/Illustration/

  fonts:
    - family: Plus Jakarta
      fonts:
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Regular.otf
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Bold.otf
          weight: 700
    - family: Grandis Extended
      fonts:
        - asset: assets/fonts/grandis_extended/GrandisExtended-Regular.ttf
        - asset: assets/fonts/grandis_extended/GrandisExtended-Thin.ttf
          weight: 300
        - asset: assets/fonts/grandis_extended/GrandisExtended-Medium.ttf
          weight: 500
        - asset: assets/fonts/grandis_extended/GrandisExtended-Bold.ttf
          weight: 700
        - asset: assets/fonts/grandis_extended/GrandisExtended-Black.ttf
          weight: 900
